//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emp1()
        {
            this.EmpAdds = new HashSet<EmpAdd>();
        }
    
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> EmpSal { get; set; }
        public string EmpCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpAdd> EmpAdds { get; set; }
    }
}
